journal_path = "~/journal"
start_of_week = "sunday"
work_days = "nova_scotia"
ai_service = "anthropic"
editor = "vim"

[clients]
    [clients.a]
    id = "ClientA"
    target_hours_per_day = 7
    rounding_increment = 15
    rounding_type = "round_up"
    notes_file_pattern = "./notes/{year}/{year}-{month}-{day}.txt"

    [clients.b]
    id = "ClientB"
    rounding_increment = 30
    rounding_type = "round"

    [clients.c]
    id = "ClientC"
    roundin_type = "none"

    [clients.d]
    id = "ClientD"

[prompts]
summarize_notes = "./prompts/summarize-notes.txt"

[anthropic]
api_key = "api key value"
model = "claude-3-5-haiku-latest"